name: bellava
description: Servicios de estilizmo 

version: 1.0.17+17

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intro_slider: ^1.0.8
  hidden_drawer_menu: ^2.0.1
  intl: ^0.16.0
  cloud_firestore: ^0.13.0+1
  generic_bloc_provider: ^1.0.9
  firebase_auth: ^0.15.3
  firebase_storage: ^3.1.5
  google_sign_in: ^4.1.1
  firebase_messaging: ^6.0.13
  percent_indicator: ^2.1.1+1
  flutter_map:
  geolocator: ^5.3.1
  location: ^3.0.0
  google_maps_flutter: ^0.5.28+1
  address_search_field: ^1.4.2
  simple_moment: ^1.0.4
  flutter_sticky_header: "^0.4.2"
  mercado_pago_mobile_checkout: ^0.0.2
  flutter_launcher_icons: ^0.7.5
  url_launcher:
  get:
  flutter_svg: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

  fonts:
  - family: Monserrat
    fonts:
        - asset: fonts/Montserrat-Regular.ttf